name: Publish Docker image

on:
  release:
    types: [published]

name: Build and Script
on:
  push:
    branches:
      - master
name: Build and Script
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: "executing remote ssh commands using ssh key"
      uses: appleboy/ssh-action@master
      with:
        host: '${{ secrets.HOST }}'
        username: '${{ secrets.USERNAME }}'
        password: '${{ secrets.PASSWORD }}'
        port: '${{ secrets.PORT }}'
        script: whoami

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ github.repository }}:${{ env.RELEASE_VERSION }}